import React from "react";
import { marked } from "marked";

marked.setOptions({ gfm: true, breaks: false });

/* Render assistant markdown in-place. We do not sanitize because content is
 * generated by our own LangGraph pipeline, not user input — script tags would
 * have to come from our own LLMs (and the report_node prompt forbids them). */
export const Markdown: React.FC<{ source: string; className?: string }> = ({ source, className }) => {
  const html = React.useMemo(() => marked.parse(source || "") as string, [source]);
  return <div className={className} dangerouslySetInnerHTML={{ __html: html }} />;
};
